'use client'

import { useEffect, useMemo, useState } from 'react'
import { Activity, Bot, Check, ChevronDown, ClipboardList, FileText, LayoutDashboard, LogIn, Menu, MessageSquare, Package, Search, Send, ShieldCheck, Users, X, AlertTriangle } from 'lucide-react'
import { customers as seedCustomers, defaultCustomer, policy, users } from '@/data/refund-data'

const nav = [{ id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard }, { id: 'customers', label: 'Customers', icon: Users }, { id: 'orders', label: 'Orders', icon: Package }, { id: 'refunds', label: 'Refund requests', icon: ClipboardList }, { id: 'logs', label: 'Agent logs', icon: Activity }, { id: 'policy', label: 'Refund policy', icon: FileText }]
const money = (value) => `₹${Number(value || 0).toLocaleString('en-IN')}`
const badge = (value) => value === 'Approved' || value === 'APPROVED' ? 'bg-emerald-50 text-emerald-700' : value === 'Denied' || value === 'DENIED' ? 'bg-rose-50 text-rose-700' : value === 'Manual Review' || value === 'MANUAL_REVIEW' ? 'bg-amber-50 text-amber-700' : 'bg-slate-100 text-slate-600'

function Avatar({ customer, small = false }) { return <div className={`${small ? 'size-8 text-[10px]' : 'size-10 text-xs'} ${customer?.color || 'bg-indigo-100 text-indigo-700'} flex shrink-0 items-center justify-center rounded-full font-bold`}>{customer?.avatar || 'CU'}</div> }
function Status({ children }) { return <span className={`rounded-full px-2 py-1 text-[10px] font-bold ${badge(children)}`}>{children}</span> }
function Stat({ label, value, icon: Icon }) { return <div className="admin-stat rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between text-slate-400"><span className="text-[11px]">{label}</span><Icon className="size-4" /></div><p className="mt-2 text-2xl font-bold tracking-tight text-slate-900">{value}</p></div> }

export default function Page() {
  const [role, setRole] = useState('admin'); const [user, setUser] = useState(null); const [login, setLogin] = useState({ email: '', password: '' })
  const [active, setActive] = useState('dashboard'); const [data, setData] = useState({ customers: seedCustomers, orders: [], refunds: [], agentLogs: [], stats: {} }); const [selected, setSelected] = useState(defaultCustomer); const [mobileOpen, setMobileOpen] = useState(false)
  const [messages, setMessages] = useState([{ role: 'agent', text: 'Hi Maya. I can verify an order and check its refund eligibility against the current policy.' }]); const [input, setInput] = useState(''); const [running, setRunning] = useState(false); const [result, setResult] = useState(null); const [error, setError] = useState('')
  useEffect(() => { fetch('/api/refund').then((res) => res.json()).then(setData).catch(() => setError('Could not load CRM data.')) }, [])
  const customer = user?.customerId ? data.customers.find((item) => item.id === user.customerId) || selected : selected
  async function signIn(event) { event.preventDefault(); const account = users.find((item) => item.role === role && item.email.toLowerCase() === login.email.trim().toLowerCase() && item.password === login.password); if (!account) return setError(role === 'admin' ? 'Invalid admin credentials.' : 'Invalid customer email or password. Each customer has a unique password: customer1001 through customer1015.'); setUser(account); setActive(role === 'admin' ? 'dashboard' : 'chat'); setError('') }
  async function sendMessage(event) { event.preventDefault(); if (!input.trim() || running) return; const text = input.trim(); setInput(''); setMessages((items) => [...items, { role: 'customer', text }]); setRunning(true); const response = await fetch('/api/refund', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ customerId: customer.id, message: text, reason: text }) }); const payload = await response.json(); setResult(payload); setMessages((items) => [...items, { role: 'agent', text: payload.message || payload.error }]); setRunning(false); fetch('/api/refund').then((res) => res.json()).then(setData) }
  async function review(refundId, action) { await fetch('/api/refund', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ refundId, action }) }); const fresh = await fetch('/api/refund').then((res) => res.json()); setData(fresh) }
  if (!user) return <Login role={role} setRole={setRole} login={login} setLogin={setLogin} signIn={signIn} error={error} />
  const visibleNav = user.role === 'admin' ? nav : [{ id: 'chat', label: 'Support chat', icon: MessageSquare }]
  return <main className="min-h-screen bg-[#f6f7fb] text-slate-900"><aside className={`${mobileOpen ? 'flex' : 'hidden'} fixed inset-y-0 left-0 z-20 w-64 flex-col border-r border-slate-200 bg-white p-4 lg:flex`}><div className="flex items-center gap-2 px-2 py-2"><div className="flex size-8 items-center justify-center rounded-lg bg-indigo-600 text-white"><ShieldCheck className="size-4" /></div><b>resolve<span className="text-indigo-600">.</span></b></div><p className="mt-8 px-2 text-[10px] font-bold uppercase tracking-widest text-slate-400">Workspace</p><nav className="mt-2 flex flex-col gap-1">{visibleNav.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => { setActive(id); setMobileOpen(false) }} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm font-medium ${active === id ? 'bg-indigo-50 text-indigo-700' : 'text-slate-500 hover:bg-slate-50'}`}><Icon className="size-4" />{label}</button>)}</nav><div className="mt-auto rounded-xl bg-indigo-50 p-3 text-xs text-indigo-800"><b>Policy protected</b><p className="mt-1 leading-4 text-indigo-700/70">Every decision is validated with backend tools.</p></div><button onClick={() => setUser(null)} className="mt-4 flex items-center gap-2 border-t border-slate-100 px-2 pt-4 text-xs text-slate-500"><LogIn className="size-4" /> Sign out</button></aside><section className="lg:ml-64"><header className="flex h-16 items-center justify-between border-b border-slate-200 bg-white px-4 lg:px-8"><div className="flex items-center gap-3"><button onClick={() => setMobileOpen(!mobileOpen)} className="lg:hidden"><Menu className="size-5" /></button><div><p className="text-[10px] text-slate-400">{user.role === 'admin' ? 'Admin console' : 'Customer portal'}</p><h1 className="text-lg font-bold">{visibleNav.find((item) => item.id === active)?.label}</h1></div></div><div className="flex items-center gap-3"><span className="hidden text-xs text-emerald-600 sm:block">● Systems operational</span><div className="flex size-8 items-center justify-center rounded-full bg-slate-900 text-xs font-bold text-white">{user.role === 'admin' ? 'JD' : 'MC'}</div></div></header><div className="p-4 lg:p-8">{active === 'chat' && <Chat customer={customer} messages={messages} input={input} setInput={setInput} sendMessage={sendMessage} running={running} result={result} />}{active === 'dashboard' && <Dashboard data={data} setActive={setActive} />}{active === 'customers' && <Customers data={data} selected={selected} setSelected={setSelected} />}{active === 'orders' && <Orders data={data} />}{active === 'refunds' && <Refunds data={data} review={review} />}{active === 'logs' && <Logs data={data} />}{active === 'policy' && <Policy />}</div></section></main>
}

function Login({ role, setRole, login, setLogin, signIn, error }) { return <main className="flex min-h-screen items-center justify-center bg-slate-950 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-8 shadow-2xl"><div className="mb-8 flex items-center gap-2"><div className="flex size-9 items-center justify-center rounded-lg bg-indigo-600 text-white"><ShieldCheck className="size-5" /></div><b className="text-lg text-blue-700">Resolve<span className="text-indigo-600">.</span></b></div><h1 className="text-2xl font-bold">Welcome back</h1><p className="mt-1 text-sm text-slate-500">Sign in to the refund operations console.</p><div className="mt-6 grid grid-cols-2 rounded-lg bg-slate-100 p-1"><button onClick={() => setRole('admin')} className={`rounded-md py-2 text-sm font-semibold ${role === 'admin' ? 'bg-white shadow-sm text-gray-500' : 'text-slate-500'}`}>Admin</button><button onClick={() => setRole('customer')} className={`rounded-md py-2 text-sm font-semibold text-gray-500 ${role === 'customer' ? 'bg-white shadow-sm' : 'text-slate-500'}`}>Customer</button></div><form onSubmit={signIn} className="mt-6 flex flex-col gap-3"><input required type="email" placeholder="Email" value={login.email} onChange={(e) => setLogin({ ...login, email: e.target.value })} className="rounded-lg border border-slate-200 px-3 py-3 text-sm outline-none focus:border-indigo-500" /><input required type="password" placeholder="Password" value={login.password} onChange={(e) => setLogin({ ...login, password: e.target.value })} className="rounded-lg border border-slate-200 px-3 py-3 text-sm outline-none focus:border-indigo-500" /><button className="rounded-lg bg-indigo-600 py-3 text-sm font-bold text-white hover:bg-indigo-700">Sign in</button></form>{error && <p className="mt-3 rounded-lg bg-rose-50 p-3 text-xs text-rose-700">{error}</p>}<p className="mt-6 rounded-lg bg-slate-50 p-3 text-[11px] leading-5 text-slate-500">Admin: admin@example.com / admin123<br />Customers: each CRM email uses password customer1001 through customer1015, matching CUS-1001 through CUS-1015.</p></div></main> }
function Dashboard({ data, setActive }) { const s = data.stats || {}; return <div><div className="mb-6 flex items-end justify-between"><div><p className="text-sm text-slate-500">Real-time overview</p><h2 className="text-3xl font-bold">Refund operations</h2></div><button onClick={() => setActive('chat')} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Open support chat</button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Total customers" value={s.customers || 15} icon={Users} /><Stat label="Total orders" value={s.orders || 15} icon={Package} /><Stat label="Refund requests" value={s.refunds || 0} icon={ClipboardList} /><Stat label="Manual review" value={s.manual || 0} icon={AlertTriangle} /></div><div className="mt-6 grid gap-5 lg:grid-cols-[1.4fr_1fr]"><section className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-bold">Decision distribution</h3><div className="mt-5 flex h-40 items-end gap-5">{[['Approved', s.approved || 0, 'bg-emerald-500'], ['Denied', s.denied || 0, 'bg-rose-500'], ['Manual', s.manual || 0, 'bg-amber-500']].map(([label, value, color]) => <div key={label} className="flex flex-1 flex-col items-center gap-2"><div className={`w-full rounded-t-lg ${color}`} style={{ height: `${Math.max(14, Number(value) * 24)}px` }} /><span className="text-xs text-slate-500">{label}</span><b>{value}</b></div>)}</div></section><section className="rounded-xl border border-indigo-100 bg-indigo-50 p-5"><h3 className="font-bold text-indigo-950">Agent guardrails</h3><ul className="mt-4 flex flex-col gap-3 text-sm text-indigo-900">{policy.rules.slice(0, 5).map((rule) => <li key={rule} className="flex gap-2"><Check className="size-4 shrink-0 text-indigo-600" />{rule}</li>)}</ul></section></div></div> }
function Customers({ data, selected, setSelected }) { return <DataPage title="Customers" subtitle="15 CRM profiles with account history"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.customers.map((c) => <button key={c.id} onClick={() => setSelected(c)} className="rounded-xl border border-slate-200 bg-white p-4 text-left hover:border-indigo-300"><div className="flex items-center gap-3"><Avatar customer={c} /><div><b className="text-sm">{c.name}</b><p className="text-xs text-slate-400">{c.id} · {c.email}</p></div></div><div className="mt-4 grid grid-cols-3 gap-2 text-xs"><span><small className="block text-slate-400">Orders</small><b>{c.orders}</b></span><span><small className="block text-slate-400">Spent</small><b>{money(c.lifetimeValue)}</b></span><span><small className="block text-slate-400">Status</small><b>{c.status}</b></span></div></button>)}</div></DataPage> }
function Orders({ data }) { return <DataPage title="Orders" subtitle="Every order linked to the CRM"><Table headers={['Order', 'Customer', 'Product', 'Amount', 'Delivery', 'Status', 'Refund']}>{data.orders.map((o) => <tr key={o.id} className="border-t border-slate-100"><td>{o.id}</td><td>{data.customers.find((c) => c.id === o.customerId)?.name}</td><td>{o.product}<small className="block text-slate-400">{o.category}</small></td><td>{money(o.amount)}</td><td>{o.deliveryDate}</td><td><Status>{o.status}</Status></td><td><Status>{o.refundStatus}</Status></td></tr>)}</Table></DataPage> }
function Refunds({ data, review }) { return <DataPage title="Refund requests" subtitle="Approve, deny, and audit every request"><Table headers={['Refund', 'Customer', 'Order', 'Amount', 'Decision', 'Created', 'Action']}>{data.refunds.map((r) => <tr key={r.id} className="border-t border-slate-100"><td>{r.id}</td><td>{data.customers.find((c) => c.id === r.customerId)?.name}</td><td>{r.orderId}</td><td>{money(r.amount)}</td><td><Status>{r.status}</Status></td><td>{new Date(r.createdAt).toLocaleDateString()}</td><td>{r.status === 'Manual Review' ? <div className="flex gap-2"><button onClick={() => review(r.id, 'approve')} className="rounded bg-emerald-600 px-2 py-1 text-[10px] font-bold text-white">Approve</button><button onClick={() => review(r.id, 'reject')} className="rounded bg-rose-600 px-2 py-1 text-[10px] font-bold text-white">Reject</button></div> : <span className="text-xs text-slate-400">Closed</span>}</td></tr>)}</Table></DataPage> }
function Logs({ data }) { return <DataPage title="Agent execution logs" subtitle="Structured tool calls, not private chain-of-thought"><div className="flex flex-col gap-3">{data.agentLogs.length === 0 ? <Empty text="No agent runs yet. Start a customer chat to create logs." /> : data.agentLogs.map((log, index) => <div key={`${log.timestamp}-${index}`} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><b>{log.tool}</b><p className="text-xs text-slate-400">{log.executionId} · {log.request}</p></div><Status>{log.status}</Status></div><pre className="mt-3 overflow-auto rounded-lg bg-slate-50 p-3 text-[10px] text-slate-600">{JSON.stringify(log.output, null, 2)}</pre></div>)}</div></DataPage> }
function Policy() { return <DataPage title="Refund policy" subtitle="The source of truth used by every agent decision"><div className="max-w-2xl rounded-xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-3"><FileText className="size-5 text-indigo-600" /><h3 className="font-bold">Refund policy v3.2</h3></div><div className="mt-5 flex flex-col gap-4">{policy.rules.map((rule, index) => <div key={rule} className="flex gap-3 border-b border-slate-100 pb-4 text-sm"><span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-indigo-50 text-xs font-bold text-indigo-600">{index + 1}</span>{rule}</div>)}</div></div></DataPage> }
function Chat({ customer, messages, input, setInput, sendMessage, running, result }) { return <div className="mx-auto max-w-4xl"><div className="mb-5 flex items-center justify-between"><div><p className="text-sm text-slate-500">Customer support</p><h2 className="text-3xl font-bold">How can we help?</h2></div><div className="flex items-center gap-2"><Avatar customer={customer} small /><span className="text-sm font-semibold">{customer.name}</span></div></div><section className="flex min-h-[600px] flex-col rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-slate-100 p-5"><div className="flex size-9 items-center justify-center rounded-full bg-indigo-600 text-white"><Bot className="size-4" /></div><div><b className="text-sm">Resolve AI</b><p className="text-xs text-emerald-600">Online · policy-aware</p></div></div><div className="flex flex-1 flex-col gap-4 overflow-y-auto p-5">{messages.map((m, i) => <div key={i} className={`flex gap-2 ${m.role === 'customer' ? 'flex-row-reverse' : ''}`}><div className={`max-w-[80%] rounded-2xl px-4 py-3 text-sm leading-5 ${m.role === 'customer' ? 'bg-slate-900 text-white' : 'bg-slate-100 text-slate-700'}`}>{m.text}</div></div>)}{running && <p className="animate-pulse text-xs text-slate-400">Resolve is calling policy tools...</p>}{result && <div className="rounded-xl border border-indigo-100 bg-indigo-50 p-4 text-xs"><b>Tool execution completed</b><div className="mt-3 flex flex-wrap gap-2">{['get_customer', 'get_order', 'get_refund_policy', 'check_refund_eligibility', result.decision === 'APPROVED' ? 'create_refund' : 'deny_refund'].map((item) => <span key={item} className="rounded-full bg-white px-2 py-1 text-indigo-700">✓ {item}</span>)}</div></div>}</div><form onSubmit={sendMessage} className="flex gap-2 border-t border-slate-100 p-4"><input value={input} onChange={(e) => setInput(e.target.value)} placeholder="Ask about an order, or request a refund for ORD-1001" className="flex-1 rounded-lg border border-slate-200 px-4 py-3 text-sm outline-none focus:border-indigo-500" /><button disabled={running || !input.trim()} className="flex size-11 items-center justify-center rounded-lg bg-indigo-600 text-white disabled:opacity-50"><Send className="size-4" /></button></form></section></div> }
function DataPage({ title, subtitle, children }) { return <div className="admin-page"><div className="admin-page-heading mb-6"><div><p className="admin-page-kicker">Admin workspace</p><h2 className="text-3xl font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div><span className="admin-live-label"><span /> CRM connected</span></div>{children}</div> }
function Table({ headers, children }) { return <div className="admin-table-wrap overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="admin-table w-full min-w-[760px] text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400"><tr>{headers.map((h) => <th key={h} className="px-4 py-3 font-bold">{h}</th>)}</tr></thead><tbody className="text-slate-700">{children}</tbody></table></div> }
function Empty({ text }) { return <div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-400">{text}</div> }
